package edu.gatech.sad.project4.entities;
// Generated Nov 26, 2015 12:46:12 AM by Hibernate Tools 4.3.1



/**
 * Professorstable generated by hbm2java
 */
public class Professorstable  implements java.io.Serializable {


     private Integer professorId;
     private String name;
     private String courses;

    public Professorstable() {
    }

	
    public Professorstable(String name) {
        this.name = name;
    }
    public Professorstable(String name, String courses) {
       this.name = name;
       this.courses = courses;
    }
   
    public Integer getProfessorId() {
        return this.professorId;
    }
    
    public void setProfessorId(Integer professorId) {
        this.professorId = professorId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCourses() {
        return this.courses;
    }
    
    public void setCourses(String courses) {
        this.courses = courses;
    }




}


